### ISSUE TITLE
`aa` does not terminate

### ISSUE THREAD

**Issue by artemlos** [DaRavenox/ADKL1#1]
Did:
1. java Reader
2. Enter `aa`

Happened:
1. The program did not respond several seconds and had to be terminated.

Expected:
1. The program terminates with info about where the word is located or that it is NOT FOUND.

**Comment by artemlos** [comment]
When repeated,

```
5
Here are the positions in the large file, use them well.
42108946
43862488
55481728
62032853
64234351
Exception in thread "main" java.io.FileNotFoundException: /info/adk16/labb1/korpus (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124)
	at Reader.FetchFromKorpus(Reader.java:237)
	at Reader.main(Reader.java:46)
```

**Comment by artemlos** [comment]
The second case is explained because I'm outside of CSC environment. However, what did trigger the first error, which looked like an infinite loop.

**Comment by artemlos** [comment]
@DaRavenox , could you please try `aa` case with a clean run (no index, ut, ut2, etc), if you are still in school?

**Comment by DaRavenox** [comment]
aa works in school

**Comment by artemlos** [comment]
@DaRavenox  Sorry, it should contain an extra space, i.e. `aa `. Does this work too?

**Comment by artemlos** [comment]
@DaRavenox , I suggest that we trim the string (i.e. so that only letters are used).
